funds:
  - id: xama
    nome: "XAMA! FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS NÃO-PADRONIZADOS"
    cnpj: "47669160000191"
    ativo: true

  - id: Kinea
    nome: "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS KINEA CRÉDITO ESTRUTURADO RESPONSABILIDADE LIMITADA"
    cnpj: "60431592000128"
    ativo: true